[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "Q",  # flake8-quotes
]
ignore = [
    "B008",
    "E501", # длина строк — не строгая
]

[tool.ruff.format]
quote-style = "double"
